npm install --save @gregfrench/react-native-wheel-picker@1.2.5
npm install --save @mapbox/geo-viewport@0.4.0
npm install --save @react-native-community/async-storage@1.11.0
npm install --save @react-native-community/slider@3.0.3
npm install --save @react-native-mapbox-gl/maps@8.0.0
npm install --save async-mutex@0.2.4
npm install --save buffer@5.6.0
npm install --save charenc@0.0.2
npm install --save convert-string@0.1.0
npm install --save deprecated-react-native-listview@0.0.6
npm install --save react-native-ble-manager@^7.3.1
npm install --save react-native-cli@2.0.1
npm install --save react-native-flip-toggle-button@1.0.8
npm install --save react-native-fs@2.16.6
npm install --save react-native-platform-touchable@1.1.1
npm install --save react-native-safe-area-context@3.1.1
npm install --save react-native-vector-icons@6.6.0